version: '3.7'

services:
  metar-service:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - 8089:8089
    depends_on:
      - postgres
  postgres:
    image: postgres:11.6
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
